// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmiyzocmunlelyoswemp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaXl6b2NtdW5sZWx5b3N3ZW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTUxODYsImV4cCI6MjA2MjU3MTE4Nn0.7GVwnIJGj1h7hPBHViwJOVT3gCsivNe869CfP7VnBxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);